if(EXISTS "/Users/shree/Downloads/Music-Streaming-Service/src/libs/som/test/test-som[1]_tests.cmake")
  include("/Users/shree/Downloads/Music-Streaming-Service/src/libs/som/test/test-som[1]_tests.cmake")
else()
  add_test(test-som_NOT_BUILT test-som_NOT_BUILT)
endif()
